### ISSUE TITLE
Rail GTFS feeds are invalid

### ISSUE THREAD

**Issue by marcusyoung** [planarnetwork/feeds.planar.network#1]
Hi,

There seems to be a problem with the GTFS feeds for Rail. They fail validation due to duplicate route_id and trip_id affecting feeds from various dates. 

For example, this extract from the latest feed trips.txt. In this small section alone there are multiple duplicates of trip_id (409078, 409089 and 409100) which in the specification must be unique:

route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,wheelchair_accessible,bikes_allowed
408729,42,**409078**,Z01507,,0,0,0
408729,42,**409078**,Z01507,,0,0,0
408729,42,**409078**,Z01507,,0,0,0
408729,17,409073,Z01507,,0,0,0
408729,41,409074,Z01507,,0,0,0
408729,24,409075,Z01507,,0,0,0
408729,18,409076,Z01507,,0,0,0
408729,44,409077,Z01507,,0,0,0
408729,42,409078,Z01507,,0,0,0
408729,25,409080,Z01507,,0,0,0
408729,42,**409089**,Z01509,,0,0,0
408729,42,**409089**,Z01509,,0,0,0
408729,42,**409089**,Z01509,,0,0,0
408729,17,409084,Z01509,,0,0,0
408729,41,409085,Z01509,,0,0,0
408729,24,409086,Z01509,,0,0,0
408729,18,409087,Z01509,,0,0,0
408729,45,409088,Z01509,,0,0,0
408729,42,**409089**,Z01509,,0,0,0
408729,20,409090,Z01509,,0,0,0
408729,25,409091,Z01509,,0,0,0
408729,42,**409100**,Z01511,,0,0,0
408729,42,**409100**,Z01511,,0,0,0
408729,42,**409100**,Z01511,,0,0,0

Another example, this from the 23 October 2018 feed, routes.txt. Repeated route_id 406476. route_id must be unique in the spec:

route_id,agency_id,route_short_name,route_long_name,route_type,route_text_color,route_color,route_url,route_desc
405755,,Z:NBG->NBG,Z train service from NBG to NBG,2,,,,Train. Standard class only. Reservation not possible
405808,,Z:ENN->ENN,Z train service from ENN to ENN,2,,,,Train. Standard class only. Reservation not possible
405872,,Z:STQ->STQ,Z boat service from STQ to STQ,4,,,,Boat. Standard class only. Reservation not possible
**406476**,,Z:STQ->SOU,Z bus service from STQ to SOU,3,,,,Bus. Standard class only. Reservation not possible
**406476**,,Z:SOU->SOU,Z bus service from SOU to SOU,3,,,,Bus. Standard class only. Reservation not possible
406479,,Z:XRD->XRD,Z boat service from XRD to XRD,4,,,,Boat. Standard class only. Reservation not possible
406617,,Z:PMH->PMS,Z bus service from PMH to PMS,3,,,,Bus. Standard class only. Reservation not possible
406672,,Z:PMH->PMH,Z boat service from PMH to PMH,4,,,,Boat. Standard class only. Reservation not possible

**Comment by linusnorton** [comment]
@marcusyoung sorry I missed this issue. Is it still a problem? Do you have a tool I use to validate the feed?
