### ISSUE TITLE
Bucket no longer exists

### ISSUE THREAD

**Issue by roadrouting** [planarnetwork/feeds.planar.network#2]
When trying to access one of the feed URLs (e.g. https://s3.eu-west-2.amazonaws.com/feeds.planar.network/gb-rail-latest.zip), the user is presented with the following error:

```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>feeds.planar.network</BucketName>
<RequestId>KQ9R28WQ96N1PXBJ</RequestId>
<HostId>8M/JhwxE+huqVy85Am1rs9nRbxV03X50Lsr8kOUSO+rqtB6QQ8xb1AaGQCebK9tE5G8oxsscE+k=</HostId>
</Error>
```

Is this service still active?

**Comment by linusnorton** [comment]
No unfortunately not, I couldn't find any way to sustainably fund it

**Comment by roadrouting** [comment]
Understand - thanks for the service and projects!
